#
# Build configuration for Circle CI
#

general:
    artifacts:
        - /home/ubuntu/myTaxiDemoApp/app/build/outputs/apk/

machine:
    java:
        version: oraclejdk8
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-26.0.2,android-26,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
        - cp -r licenses/. $ANDROID_HOME/licenses

test:
    override:
        - (./gradlew assemble):
            timeout: 360